### ISSUE TITLE
Missing dependency in map-import component

### ISSUE THREAD

**Issue by guillefhc** [osiris-indoor/osiris#1]
There is an error when building the map-import component

Failed to execute goal on project map-import: Could not resolve dependencies for project com.bitmonlab.batch:map-import:jar:0.0.1-SNAPSHOT: Could not find artifact org.opentripplanner:opentripplanner-graph-builder:jar:0.9.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by angelramosalvarez** [comment]
We have included opentripplanner libraries inside code source and linked by maven, because these version of libraries are not in a public repository.
