### ISSUE TITLE
Null parameter error 

### ISSUE THREAD

**Issue by RYO2506** [osiris-indoor/osiris#2]
Hi , 
after following all the steps I got the server up and running but I got this get this error 
{\"status\":400,\"statusReason\":\"Bad Request\",\"code\":2,\"exception\":\"InvalidParametersException\",\"description\":\"Passed parameters are incorrect\",\"message\":\"Passed parameter can not be null\"}
when I use http://localhost:8020/osiris/geolocation/territory/map/metadata

any ideas about what does it mean and how to fix it ?

**Comment by mdislam** [comment]
Hi: 
Hope you are fine.

Is there any update in this issue? I am also getting the same error. Any ideas how to fix this?

**Comment by deuteros76** [comment]
This message means that the petition is missing some parameter. However we would need to see  your source code to have a clue.

**Comment by RYO2506** [comment]
I got it working by adding the  api_key in the header.

**Comment by mdislam** [comment]
Thank you @RYO2506. Your solution worked for me. I didn't add the api_key in the header.
