### ISSUE TITLE
What should be the value of a {idFeature} in REST API?

### ISSUE THREAD

**Issue by mdislam** [osiris-indoor/osiris#3]
Hi:

I am using the osiris server. I have just installed and wanted to see the results of REST APIs in browser. I can successfully run the GET methods for getting metadata and MAP file.

But, I could not get the Features by ID:
GET /osiris/geolocation/territory/feature/{idFeature}

Because, I do not understand what should be the id of a feature. Could you please give an example, like what should be the id or from where i could find out the id of a feature?

**Comment by mdislam** [comment]
I am including one example of my Query here:
I have a map with map_id "map1"
In the osirisGeoLocation Database the collection map_app_map1 has one entry like following:

`{ "_id" : "-1582", "_class" : "com.bitmonlab.osiris.commons.map.model.geojson.Feature", "type" : "Feature", "geometry" : { "_class" : "com.bitmonlab.osiris.commons.map.model.geojson.Point", "coordinates" : [ 24.54651185459, 60.16108772035 ], "type" : "Point" }, "properties" : { "@type" : "node", "@id" : "-1582" }, "propertiesRelations" : [ { "building" : "office", "min_level" : "1", "addr:country" : "FI", "@type" : "way", "name" : "Paikkatietokeskus FGI", "roof:shape" : "flat", "@id" : "-4578", "max_level" : "3", "addr:street" : "Geodeetinrinne", "addr:housename" : "Paikkatietokeskus", "addr:city" : "Kirkkonummi", "addr:housenumber" : "2" }, { "building" : "office", "min_level" : "1", "addr:country" : "FI", "@type" : "way", "name" : "Paikkatietokeskus FGI", "roof:shape" : "flat", "@id" : "-4896", "max_level" : "3", "addr:street" : "Geodeetinrinne", "addr:housename" : "Paikkatietokeskus", "addr:city" : "Kirkkonummi", "addr:housenumber" : "2" }, { "@type" : "way", "@id" : "-4901" }, { "@type" : "way", "@id" : "-4946" }, { "building" : "office", "min_level" : "1", "addr:country" : "FI", "@type" : "way", "name" : "Paikkatietokeskus FGI", "roof:shape" : "flat", "@id" : "-5235", "max_level" : "3", "addr:street" : "Geodeetinrinne", "addr:housename" : "Paikkatietokeskus", "addr:city" : "Kirkkonummi", "addr:housenumber" : "2" }, { "building" : "office", "min_level" : "1", "addr:country" : "FI", "@type" : "way", "name" : "Paikkatietokeskus FGI", "roof:shape" : "flat", "@id" : "56039328", "max_level" : "3", "addr:street" : "Geodeetinrinne", "addr:housename" : "Paikkatietokeskus", "addr:city" : "Kirkkonummi", "addr:housenumber" : "2" } ] }`

Now, I am using the -1582 as the idFeature in the GET API:

`http://192.168.0.6:8020/osiris/geolocation/territory/feature/-1582`

In header:

`api_key = map1`

Response:

`{
  "status": 404,
  "statusReason": "Not Found",
  "code": 3,
  "exception": "FeatureNotExistException",
  "description": "Feature is not found",
  "message": null
}`

**Comment by guillefhc** [comment]
What is the result of doing the following query?

http://192.168.0.6:8020/osiris/geolocation/territory/search?layer=FEATURES&pageSize=2000

**method** = POST

**In headers:**
api_key = map1
Content-Type: application/json

**The query in the body**:
{}

In my case (using my own api_key, etc) is something like this:

![image](https://cloud.githubusercontent.com/assets/5681065/14636468/f76a7898-062b-11e6-94a2-86dec93a2036.png)

**Comment by mdislam** [comment]
Here is my result. I am using the sample map provided by osiris and the map id is "my_map"

![image](https://cloud.githubusercontent.com/assets/2608597/14639986/1283f426-0648-11e6-946d-d9ef815cf724.png)

**Comment by mdislam** [comment]
BUT, if I try with following query, (layer=MAP instead of layer=FEATURES)

`http://192.168.0.6:8020/osiris/geolocation/territory/search?layer=MAP&pageSize=1`

I get response like the image

![image](https://cloud.githubusercontent.com/assets/2608597/14640241/54497204-0649-11e6-9bc5-8525219ad40d.png)

**Comment by guillefhc** [comment]
Osiris has two different collections for storing data in MongoDB; MAP and FEATURES. The first one stores all the maps that you import. The second one is designed to work with points of interest.

FEATURES includes its own methods for inserting and accessing POIs:
- POST /osiris/geolocation/territory/feature to store a feature (POI)
- PUT /osiris/geolocation/territory/feature/{idFeature} to update a feature
- DELETE /osiris/geolocation/territory/feature/{idFeature} to remove a feature
- GET /osiris/geolocation/territory/feature/{idFeature} to get a feature

In addition the search method operates with the collection assigned to the layer parameter. So, http://192.168.0.6:8020/osiris/geolocation/territory/search?layer=FEATURES&pageSize=2000 with the api_key in the header and {} in the search body, returns the first 2000 results in the FEATURES collection.

In your case, your FEATURES collection is empty. This is right becase you have not inserted (POST /osiris/geolocation/territory/feature) anything in it. As the collection is empty, if you try to get a feature ( 
GET /osiris/geolocation/territory/feature/{idFeature} ) you will obtain an error message.

I hope this will help you

**Comment by mdislam** [comment]
Thank you for the guidelines. I can now create feature and get feature. Thanks
